Add coverage report
netdata/charts pull request #59
Opened 2022-02-25 14:57 UTC by ivangergo3

Added similar test-coverage report as we have in "cound-frontend"

So from now on, all tests will be executed when a pull request is being created.

And we will publish the results into google cloud, so we can check the current status [here](https://github.com/netdata/test-automation/wiki/Netdata-Test-Coverage-Report)

Could you please check this change? And if you have any concerns let me know

2022-03-01 12:32 UTC, novykh requested changes

2022-03-01 12:32 UTC, novykh commented on .github/workflows/tests.yml
> +    branches: [master, develop]
there is no master or develop. Only `main` branch

2022-03-03 10:14 UTC, ivangergo3 commented on package.json
> +    "clean": "./node_modules/rimraf/bin.js lib dist es coverage",
No there was not, I changed it back to the original

2022-03-04 14:49 UTC, ivangergo3 commented
@jjtsou can you please help me out here? I changed what you asked, but squashed the commit. And I cannot resolve the request

2022-03-04 14:57 UTC, novykh approved these changes

2022-03-08 10:42 UTC, ivangergo3 commented
@novykh  do you think it can be merged now?

2022-03-16 09:17 UTC, merged